### ISSUE TITLE
Unable to delete signature source with special characters

### ISSUE THREAD

**Issue by jamie-34254** [CybercentreCanada/assemblyline-ui#278]
I accidentally mixed up the source name and URL and managed to create this:
![image](https://user-images.githubusercontent.com/1857320/134718815-c5765c49-5a30-4e5f-9f2b-9ce191300297.png)

Unfortunately it's not possible to delete it via the UI:
![image](https://user-images.githubusercontent.com/1857320/134718873-2322f533-b7aa-4a24-8fab-4f27346936d0.png)

**Comment by cccs-sgaron** [comment]
Alright I'l fix this.
