### ISSUE TITLE
Challenging to troubleshoot oAuth errors

### ISSUE THREAD

**Issue by jamie-34254** [CybercentreCanada/assemblyline-ui#282]
Unfortunately due to the way oAuth errors are caught and handled it becomes very challenging to troubleshoot any code errors:

https://github.com/CybercentreCanada/assemblyline-ui/blob/0594f3ab785d27c5b63511c9b329c70d556c78af/assemblyline_ui/api/v4/authentication.py#L579-L587

![image](https://user-images.githubusercontent.com/1857320/134933644-725ceb2a-2450-4d48-8cf2-3e57b0a67283.png)

Ideally there would still be a stack trace in the logs, or at least a flag to enable logging for that

Offtopic: I tried to build the image myself with the Dockerfile `docker/ui/Dockerfile` and a modification to print stack traces but  I get the error `ModuleNotFoundError: No module named 'assemblyline_ui.patched'` but I don't see where this patched thing is coming from?

**Comment by cccs-sgaron** [comment]
With PR #287, we make a distinction between oAuth exceptions and other exceptions. When other exceptions are triggered, you should have a stack trace of the issue in your logs.

**Comment by jamie-34254** [comment]
Thanks Steve, I'll give this a go now!

**Comment by cccs-sgaron** [comment]
@jamie-34254 just hang on for a bit this is not merged to master yet. This is only live on dev containers.
