### ISSUE TITLE
Error 500 on add service from ui

### ISSUE THREAD

**Issue by antarus** [CybercentreCanada/assemblyline-ui#350]
hello,

When I try to add a service via the ui (by pasting a service_manifest.yml), I get the following error:

>api_error_message: "↵  File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app↵    response = self.full_dispatch_request()↵  File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request↵    rv = self.handle_user_exception(e)↵  File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request↵    rv = self.dispatch_request()↵  File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request↵    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)↵  File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_ui/api/base.py", line 188, in base↵    return func(*args, **kwargs)↵  File "/var/lib/assemblyline/.local/lib/python3.9/site-packages/assemblyline_ui/api/v4/service.py", line 137, in add_service↵    service['update_channel'] = tmp_service['update_channel']↵UnboundLocalError: local variable 'tmp_service' referenced before assignment"
api_response: ""
api_server_version: "4.2.0.5"
api_status_code: 500

**Comment by cccs-rs** [comment]
https://github.com/CybercentreCanada/assemblyline-ui/pull/360
