### ISSUE TITLE
New encoding format for /api/v4/file/download/<sha256>

### ISSUE THREAD

**Issue by adib0u** [CybercentreCanada/assemblyline-ui#376]
Hello,

Would it be possible to add a new file encoding method when using the endpoint `/api/v4/file/download/<sha256>` to download a file as a zip/password ?

A nice feature could be to be able to configure/change the password used for the zip.

Thanks for your help :)

**Comment by cccs-rs** [comment]
Resolved in release 4.2.0.86. See: https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.2.0.stable86
