### ISSUE TITLE
Disabling service removes imported signatures from the system.

### ISSUE THREAD

**Issue by ociappara** [CybercentreCanada/assemblyline-ui#576]
### Issue
If you disable YARA or ConfigExtractor service, the signatures that had been imported are removed from the system. If you Enable the services again, you will need to delete the key from Redis to be able to pull down the signatures again.

### Expected
Either signatures persist service shutdown, or when service is enabled again, signatures are automatically pulled again without the need for manual intervention.

### Steps to reproduce
1. Make sure Yara and ConfigExtractor have sources up to date, and you can see the signatures in the system.
2. Under "_Service Management_" Disable the Yara and ConfigExtractor services.
3. Go back to "_Update Sources_" click the fingerprint to find the signatures for that source, notice that the signatures are no longer in the system. 
4. Go back to "_Service Management_" and Enable Yara and ConfigExtractor again.
5. Repeat Step 3 and notice no signatures are in the system.
6. Click the download signatures button in "_Update Sources_" and notice that the signatures are not updated.

### Workaround
1. Log in to the redis-persistant pod
2. Enter redis-cli
3. Delete the keys for Yara and ConfigExtractor
4. Restart pods
5. Pull sources again, and you should be able to see the signatures again, if not delete the redis key again and do another update without a restart.

**Comment by cccs-rs** [comment]
This should be resolve in: https://github.com/CybercentreCanada/assemblyline/releases/tag/v4.3.1.stable2

If this isn't the case, feel free to re-open the issue! 😀
